export const RECOMMENDATION_WIDGET_WIDTH_COMPACT = "225px";

export const RECOMMENDATION_MAX_DESRIPTION_LENGTH_COMPACT = 60;
export const RECOMMENDATION_MAX_DESRIPTION_LENGTH_EXPANDED = 170;
export const RECOMMENDATION_MENU_MAX_DESCRIPTION_LENGTH = 280;
